### ISSUE TITLE
glob2 doesn't compile on ubuntu-20.04

### ISSUE THREAD

**Issue by spikebike** [Globulation2/glob2#25]
I installed scons-2.5.1 from source to compile glob2.  It compiled for awhile, but:
```g++ -o build/src/AIEcho.o -c -g -Wall -DHAVE_CONFIG_H -D_GNU_SOURCE=1 -D_REENTRANT -Ilibgag/include -I. -Ilibusl/src -I/usr/include/SDL src/AIEcho.cpp
src/AIEcho.cpp: In member function 'bool AIEcho::SearchTools::enemy_building_iterator::operator!=(const AIEcho::SearchTools::enemy_building_iterator&) const':
src/AIEcho.cpp:4390:102: error: cannot convert 'boost::logic::tribool' to 'bool' in return
 4390 | eturn is_end!=rhs.is_end || team!=rhs.team || building_type!=rhs.building_type || level!=rhs.level || construction_site!=rhs.construction_site;
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                    |
      |                                                                                                    boost::logic::tribool

scons: *** [build/src/AIEcho.o] Error 1
scons: building terminated because of errors.
```

**Comment by cajomar** [comment]
I also had the problem on Ubuntu 20.04
I casted the construction sight comparison into a bool like so:
``` C++
return is_end!=rhs.is_end || team!=rhs.team || building_type!=rhs.building_type || level!=rhs.level || (bool)(construction_site!=rhs.construction_site);
```
And it worked for me. Compiled, at least.
I'm not familiar with the source code, nor have I used the `boost::logic::tribool`, so it might cause some nasty bugs later on.

**Comment by Giszmo** [comment]
This is a duplicate of #22

**Comment by stephanemagnenat** [comment]
This should be fixed by #28.
